// 「全部快速鍵」說明欄的中文翻譯；key 是 keymaps.js 裡的英文原文。
// 手動維護：./update.sh 重新匯出後若出現新的英文說明，在這裡補一行即可，查不到的會顯示原文。
window.DESC_ZH = {
  // which-key 群組
  "+noice": "noice 訊息群組",
  "+test": "測試群組",
  "AI/Claude Code": "AI／Claude Code 群組",

  // 插入模式：切一段新的復原點
  ",<C-G>u": "輸入逗號，並切一段新的復原點",
  ".<C-G>u": "輸入句點，並切一段新的復原點",
  ";<C-G>u": "輸入分號，並切一段新的復原點",

  // quickfix / location list / 檔案清單 / tag 清單
  ":clast": "跳到 quickfix 清單最後一項",
  ":cnfile": "跳到 quickfix 下一個檔案的第一項",
  ":cpfile": "跳到 quickfix 上一個檔案的第一項",
  ":crewind": "跳到 quickfix 清單第一項",
  ":llast": "跳到 location list 最後一項",
  ":lnext": "跳到 location list 下一項",
  ":lnfile": "跳到 location list 下一個檔案的第一項",
  ":lpfile": "跳到 location list 上一個檔案的第一項",
  ":lprevious": "跳到 location list 上一項",
  ":lrewind": "跳到 location list 第一項",
  ":next": "跳到檔案清單下一個檔案",
  ":previous": "跳到檔案清單上一個檔案",
  ":last": "跳到檔案清單最後一個檔案",
  ":rewind": "跳到檔案清單第一個檔案",
  ":ptnext": "在預覽視窗跳到下一個 tag",
  ":ptprevious": "在預覽視窗跳到上一個 tag",
  ":tlast": "跳到 tag 清單最後一個",
  ":trewind": "跳到 tag 清單第一個",

  // vim 內建預設鍵
  ":help &-default": "重複上一次的取代（同 :&&）",
  ":help Y-default": "從游標複製到行尾（同 y$）",
  ":help i_CTRL-U-default": "刪掉游標前這一行輸入的內容（可復原）",
  ":help i_CTRL-W-default": "刪掉游標前一個單字（可復原）",
  ":help v_#-default": "往回搜尋選取的文字",
  ":help v_star-default": "往下搜尋選取的文字",
  ":help v_@-default": "對選取的每一行執行 macro",

  // 視窗與分割
  ":split<CR>": "上下分割視窗",
  ":vsplit<CR>": "左右分割視窗",
  ":tabedit": "開新標籤頁，接著輸入檔名",
  ":tabnext<CR>": "下一個標籤頁",
  ":tabprev<CR>": "上一個標籤頁",
  "<C-W>h": "跳到左邊的視窗",
  "<C-W>j": "跳到下面的視窗",
  "<C-W>k": "跳到上面的視窗",
  "<C-W>l": "跳到右邊的視窗",
  "<lt>gv": "往左縮排，並保持選取",
  ">gv": "往右縮排，並保持選取",
  "ggVG": "全選",

  // matchit：括號與關鍵字配對
  "<Plug>(MatchitNormalForward)": "跳到對應的括號或關鍵字",
  "<Plug>(MatchitNormalBackward)": "往回跳到對應的括號或關鍵字",
  "<Plug>(MatchitNormalMultiForward)": "跳到外層區塊的結尾",
  "<Plug>(MatchitNormalMultiBackward)": "跳到外層區塊的開頭",
  "<Plug>(MatchitOperationForward)": "配合操作指令，作用到對應的括號或關鍵字",
  "<Plug>(MatchitOperationBackward)": "配合操作指令，往回作用到對應的括號或關鍵字",
  "<Plug>(MatchitOperationMultiForward)": "配合操作指令，作用到外層區塊的結尾",
  "<Plug>(MatchitOperationMultiBackward)": "配合操作指令，作用到外層區塊的開頭",
  "<Plug>(MatchitVisualForward)": "選取到對應的括號或關鍵字",
  "<Plug>(MatchitVisualBackward)": "往回選取到對應的括號或關鍵字",
  "<Plug>(MatchitVisualMultiForward)": "選取到外層區塊的結尾",
  "<Plug>(MatchitVisualMultiBackward)": "選取到外層區塊的開頭",
  "<Plug>(MatchitVisualTextObject)": "選取整組對應的括號或區塊",

  // mini.pairs：成對符號
  "Open action for \"()\" pair": "輸入 ( 時自動補上 )",
  "Open action for \"[]\" pair": "輸入 [ 時自動補上 ]",
  "Open action for \"{}\" pair": "輸入 { 時自動補上 }",
  "Close action for \"()\" pair": "輸入 ) 時跳過已經有的 )",
  "Close action for \"[]\" pair": "輸入 ] 時跳過已經有的 ]",
  "Close action for \"{}\" pair": "輸入 } 時跳過已經有的 }",
  "Closeopen action for '\"\"' pair": "輸入 \" 時自動補成一對，或跳過已經有的",
  "Closeopen action for \"''\" pair": "輸入 ' 時自動補成一對，或跳過已經有的",
  "Closeopen action for \"``\" pair": "輸入 ` 時自動補成一對，或跳過已經有的",
  "MiniPairs <BS>": "退格時，成對符號一起刪掉",
  "MiniPairs <CR>": "在成對符號中間換行，自動排好縮排",
  "Toggle Mini Pairs": "開／關括號自動配對",

  // 移動與編輯
  "Down": "往下一行",
  "Up": "往上一行",
  "Move Down": "把這行往下搬",
  "Move Up": "把這行往上搬",
  "Add empty line above cursor": "在游標上方插入空行",
  "Add empty line below cursor": "在游標下方插入空行",
  "Save File": "存檔",
  "Scroll Forward": "往下翻一頁",
  "Scroll Backward": "往上翻一頁",
  "Escape and Clear hlsearch": "離開目前模式，並清掉搜尋標記",
  "Redraw / Clear hlsearch / Diff Update": "重畫畫面／清掉搜尋標記／更新 diff",
  "Open parent directory": "打開上一層目錄",
  "Opens filepath or URI under cursor with the system handler (file explorer, web browser, …)":
    "用系統預設程式開啟游標所在的路徑或網址（檔案總管、瀏覽器⋯）",
  "Keywordprg": "用外部說明程式查游標所在的字",
  "Registers": "列出暫存器（register）內容",
  "Jump to Mark": "跳到標記（mark）",
  "Jumplist": "跳躍紀錄",

  // 註解
  "Toggle comment": "加／取消註解",
  "Toggle comment line": "整行加／取消註解",
  "Add Comment Above": "在上面加一行註解",
  "Add Comment Below": "在下面加一行註解",
  "Comment textobject": "選取整段註解",

  // 文字物件
  "Around textobject": "選整個文字物件（含外框）",
  "Around next textobject": "選下一個文字物件（含外框）",
  "Around last textobject": "選上一個文字物件（含外框）",
  "Inside textobject": "選文字物件的內容（不含外框）",
  "Inside next textobject": "選下一個文字物件的內容",
  "Inside last textobject": "選上一個文字物件的內容",
  "Move to left \"around\"": "跳到區塊的左邊界",
  "Move to right \"around\"": "跳到區塊的右邊界",

  // flash / treesitter
  "Flash": "Flash：打兩個字直接跳過去",
  "Flash Treesitter": "Flash：依語法結構選取區塊",
  "Remote Flash": "Flash：跳去別處做完操作再跳回來",
  "Treesitter Search": "Flash：依語法結構搜尋跳躍",
  "Treesitter Incremental Selection": "依語法結構逐層擴大選取",
  "Select next node": "選下一個語法節點",
  "Select previous node": "選上一個語法節點",
  "Select next sibling node": "選下一個同層語法節點",
  "Select previous sibling node": "選上一個同層語法節點",
  "Inspect Tree": "看 Treesitter 語法樹",
  "Inspect Pos": "看游標這個位置的語法與 highlight",

  // 搜尋
  "Next Search Result": "下一個搜尋結果",
  "Prev Search Result": "上一個搜尋結果",
  "Search and Replace": "全專案搜尋並取代",
  "Search History": "搜尋歷史",
  "Search Highlight Groups": "搜尋 highlight 群組",
  "Grep (Root Dir)": "搜內容（專案根目錄）",
  "Grep (cwd)": "搜內容（目前工作目錄）",
  "Word (Root Dir)": "搜尋游標所在的字（專案根目錄）",
  "Word (cwd)": "搜尋游標所在的字（目前工作目錄）",
  "Selection (Root Dir)": "搜尋選取的文字（專案根目錄）",
  "Selection (cwd)": "搜尋選取的文字（目前工作目錄）",
  "Resume": "重開上一次的搜尋結果",

  // 找檔案與 picker
  "Find Files (Root Dir)": "找檔案（專案根目錄）",
  "Find Files (cwd)": "找檔案（目前工作目錄）",
  "Find Files (git-files)": "找檔案（只找 git 管的）",
  "Find Config File": "找 nvim 設定檔",
  "New File": "開新檔案",
  "Recent": "最近開過的檔案",
  "Recent (cwd)": "最近開過的檔案（目前工作目錄）",
  "Explorer NeoTree (Root Dir)": "檔案樹（專案根目錄）",
  "Explorer NeoTree (cwd)": "檔案樹（目前工作目錄）",
  "Buffer Lines": "在目前檔案裡搜尋行",
  "Commands": "列出所有指令",
  "Command History": "指令歷史",
  "Auto Commands": "列出所有 autocommand",
  "Help Pages": "搜尋說明文件",
  "Man Pages": "搜尋 man 說明頁",
  "Key Maps": "搜尋所有快速鍵",
  "Buffer Keymaps (which-key)": "目前檔案能用的快速鍵（which-key）",
  "Window Hydra Mode (which-key)": "視窗操作模式，下方列出能按的鍵",

  // 已開的檔案（buffer）
  "Buffers": "列出已開的檔案",
  "Buffers (all)": "列出全部已開的檔案（含隱藏）",
  "Buffer Explorer": "已開檔案瀏覽器",
  "Switch Buffer": "切換已開的檔案",
  "Switch to Other Buffer": "切回上一個看過的檔案",
  "Pick Buffer": "每個檔名旁顯示字母，按字母跳過去",
  "Next Buffer": "下一個檔案",
  "Prev Buffer": "上一個檔案",
  "Move buffer next": "把這個檔案在檔名列往右挪",
  "Move buffer prev": "把這個檔案在檔名列往左挪",
  "Toggle Pin": "釘選／取消釘選這個檔案",
  "Delete Buffer": "關掉目前檔案",
  "Delete Buffer and Window": "關掉目前檔案，連視窗一起關",
  "Delete Other Buffers": "關掉其他檔案",
  "Delete Buffers to the Left": "關掉左邊全部檔案",
  "Delete Buffers to the Right": "關掉右邊全部檔案",
  "Delete Invisible Buffers": "關掉沒顯示在畫面上的檔案",
  "Delete Non-Pinned Buffers": "關掉沒釘選的檔案",

  // 標籤頁
  "New Tab": "開新標籤頁",
  "Next Tab": "下一個標籤頁",
  "Previous Tab": "上一個標籤頁",
  "First Tab": "第一個標籤頁",
  "Last Tab": "最後一個標籤頁",
  "Close Tab": "關掉這個標籤頁",
  "Close Other Tabs": "關掉其他標籤頁",

  // 視窗
  "Go to Left Window": "跳到左邊的視窗",
  "Go to Right Window": "跳到右邊的視窗",
  "Go to Upper Window": "跳到上面的視窗",
  "Go to Lower Window": "跳到下面的視窗",
  "Split Window Below": "往下分割視窗",
  "Split Window Right": "往右分割視窗",
  "Delete Window": "關掉這格視窗",
  "Increase Window Width": "視窗變寬",
  "Decrease Window Width": "視窗變窄",
  "Increase Window Height": "視窗變高",
  "Decrease Window Height": "視窗變矮",
  "Toggle Zoom": "這格視窗滿版 ⇄ 還原",
  "Toggle Zoom Mode": "這格視窗滿版 ⇄ 還原",
  "Toggle Zen Mode": "開／關禪模式",
  "Terminal (Root Dir)": "開終端機（專案根目錄）",
  "Terminal (cwd)": "開終端機（目前工作目錄）",
  "Quit All": "離開 nvim",

  // 程式碼與 LSP
  "Format": "格式化",
  "Format Injected Langs": "格式化內嵌的其他語言",
  "Goto Symbol": "跳到這個檔案的函式或類別",
  "Goto Symbol (Workspace)": "跳到整個專案的函式或類別",
  "Symbols (Trouble)": "函式與類別大綱（Trouble）",
  "LSP references/definitions/... (Trouble)": "LSP 參照、定義等清單（Trouble）",
  "Mason": "開啟 Mason（安裝 LSP 與工具）",
  "vim.lsp.buf.code_action()": "code action（自動修正建議）",
  "vim.lsp.buf.document_symbol()": "列出這個檔案的函式與類別",
  "vim.lsp.buf.implementation()": "跳到實作",
  "vim.lsp.buf.references()": "列出誰用到它",
  "vim.lsp.buf.rename()": "重新命名（全專案一起改）",
  "vim.lsp.buf.type_definition()": "跳到型別定義",
  "vim.lsp.codelens.run()": "執行 code lens",
  "vim.snippet.jump if active, otherwise <Tab>": "在 snippet 裡跳到下一個空格，否則就是 Tab",
  "vim.snippet.jump if active, otherwise <S-Tab>": "在 snippet 裡跳到上一個空格，否則就是 Shift+Tab",

  // 錯誤與警告（diagnostics）
  "Diagnostics": "問題清單（錯誤與警告）",
  "Diagnostics (Trouble)": "問題清單（Trouble）",
  "Buffer Diagnostics": "目前檔案的問題清單",
  "Buffer Diagnostics (Trouble)": "目前檔案的問題清單（Trouble）",
  "Line Diagnostics": "顯示這行的問題訊息",
  "Show diagnostics under the cursor": "顯示游標所在的問題訊息",
  "Next Diagnostic": "下一個問題",
  "Prev Diagnostic": "上一個問題",
  "Next Error": "下一個錯誤",
  "Prev Error": "上一個錯誤",
  "Next Warning": "下一個警告",
  "Prev Warning": "上一個警告",
  "Jump to the first diagnostic in the current buffer": "跳到這個檔案的第一個問題",
  "Jump to the last diagnostic in the current buffer": "跳到這個檔案的最後一個問題",
  "Toggle Diagnostics": "開／關問題提示",
  "Quickfix List": "quickfix 清單",
  "Quickfix List (Trouble)": "quickfix 清單（Trouble）",
  "Location List": "location list 清單",
  "Location List (Trouble)": "location list 清單（Trouble）",
  "Next Trouble/Quickfix Item": "Trouble／quickfix 清單的下一項",
  "Previous Trouble/Quickfix Item": "Trouble／quickfix 清單的上一項",
  "Todo": "TODO 註解清單",
  "Todo (Trouble)": "TODO 註解清單（Trouble）",
  "Todo/Fix/Fixme": "TODO／FIX／FIXME 註解清單",
  "Todo/Fix/Fixme (Trouble)": "TODO／FIX／FIXME 註解清單（Trouble）",
  "Next Todo Comment": "下一個 TODO 註解",
  "Previous Todo Comment": "上一個 TODO 註解",

  // Git
  "Status": "Git 狀態",
  "Commits": "列出 commit",
  "Git Log (cwd)": "Git 紀錄（目前工作目錄）",
  "Git Current File History": "這個檔案的修改紀錄",
  "Git Diff (files)": "看有哪些檔案改過",
  "Git Explorer": "Git 變更瀏覽器",
  "Git Stash": "列出 git stash",
  "Git Blame Line": "看這行是誰改的",
  "Git Browse (open)": "用瀏覽器開這行的 Git 頁面",
  "Git Browse (copy)": "複製這行的 Git 網頁連結",
  "Lazygit (Root Dir)": "lazygit（專案根目錄）",
  "Lazygit (cwd)": "lazygit（目前工作目錄）",

  // Claude
  "Toggle Claude": "開／關 Claude 側欄",
  "Focus Claude": "跳到 Claude 視窗",
  "Resume Claude": "挑一個舊的 Claude 對話接續",
  "Continue Claude": "接續上一次 Claude 對話",
  "Add current buffer": "把目前檔案加進 Claude",
  "Send to Claude": "把選取的內容送給 Claude",
  "Accept diff": "接受 Claude 的修改",
  "Deny diff": "拒絕 Claude 的修改",

  // 測試
  "Run Nearest (Neotest)": "跑游標所在的測試（Neotest）",
  "Run File (Neotest)": "跑這個測試檔（Neotest）",
  "Run All Test Files (Neotest)": "跑全部測試檔（Neotest）",
  "Run Last (Neotest)": "重跑上一次的測試（Neotest）",
  "Stop (Neotest)": "停止測試（Neotest）",
  "Attach to Test (Neotest)": "附加到執行中的測試（Neotest）",
  "Show Output (Neotest)": "看測試輸出（Neotest）",
  "Toggle Output Panel (Neotest)": "開／關測試輸出面板（Neotest）",
  "Toggle Summary (Neotest)": "開／關測試清單側欄（Neotest）",
  "Toggle Watch (Neotest)": "開／關測試自動重跑（Neotest）",
  "Debug Nearest": "偵錯游標所在的測試",

  // 偵錯（DAP）
  "Run/Continue": "開始或繼續偵錯",
  "Run with Args": "帶參數開始偵錯",
  "Run Last": "重跑上一次的偵錯",
  "Run to Cursor": "執行到游標這行",
  "Go to Line (No Execute)": "把執行位置移到這行（不執行）",
  "Step Over": "執行下一行",
  "Step Into": "進入函式",
  "Step Out": "跳出函式",
  "Pause": "暫停偵錯",
  "Terminate": "結束偵錯",
  "Toggle Breakpoint": "設定／取消中斷點",
  "Breakpoint Condition": "設定有條件的中斷點",
  "Eval": "看變數或運算式的值",
  "Dap UI": "開／關偵錯畫面",
  "Widgets": "偵錯小工具（變數、堆疊等）",
  "Session": "偵錯工作階段資訊",
  "Toggle REPL": "開／關 REPL 主控台",
  "Toggle Profiler": "開／關效能分析",
  "Toggle Profiler Highlights": "開／關效能分析標記",
  "Profiler Scratch Buffer": "效能分析結果的暫存檔",

  // 工作階段（session）
  "Restore Session": "還原這個目錄的工作階段",
  "Restore Last Session": "還原上一次的工作階段",
  "Select Session": "挑一個工作階段還原",
  "Don't Save Current Session": "這次離開不要存工作階段",

  // 通知與訊息
  "Notification History": "通知紀錄",
  "Dismiss All": "關掉所有通知",
  "Dismiss All Notifications": "關掉所有通知",
  "Noice All": "所有 noice 訊息",
  "Noice History": "noice 訊息紀錄",
  "Noice Last Message": "最後一則 noice 訊息",
  "Noice Picker (Telescope/FzfLua)": "用搜尋視窗翻 noice 訊息",

  // 外觀與開關
  "Colorscheme with Preview": "換配色（可即時預覽）",
  "Toggle Dark Background": "切換深色／淺色背景",
  "Toggle Line Numbers": "開／關行號",
  "Toggle Relative Number": "開／關相對行號",
  "Toggle Wrap": "開／關自動換行",
  "Toggle Spelling": "開／關拼字檢查",
  "Toggle Indent Guides": "開／關縮排參考線",
  "Toggle Inlay Hints": "開／關型別提示（inlay hints）",
  "Toggle Conceal Level": "開／關語法隱藏（conceal）",
  "Toggle Treesitter Highlight": "開／關 Treesitter 語法上色",
  "Toggle Animations": "開／關動畫",
  "Toggle Smooth Scroll": "開／關平滑捲動",
  "Toggle Dimming": "開／關非焦點區域變暗",
  "Toggle Tabline": "開／關上方檔名列",
  "Toggle Auto Format (Global)": "開／關自動格式化（全部）",
  "Toggle Auto Format (Buffer)": "開／關自動格式化（只這個檔案）",
  "Toggle Scratch Buffer": "開／關暫存檔（scratch buffer）",
  "Select Scratch Buffer": "挑一個暫存檔（scratch buffer）",

  // 其他
  "Lazy": "開啟 Lazy 外掛管理器",
  "LazyVim Changelog": "LazyVim 更新紀錄"
};
